#!/usr/bin/env python3
"""Aggregate distributed Markdown frontmatter into a registry cache and human-readable MD.

Run from repo root or any location:
    python scripts/aggregate_registry.py
"""

from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
REGISTRY_CACHE = REPO_ROOT / ".registry_cache.json"
REGISTRY_MD = REPO_ROOT / "docs" / "reference" / "registry" / "DOC_REGISTRY.md"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def extract_governed_entries() -> list[dict[str, Any]]:
    entries = []
    # Find markdown files in repo root and docs/
    md_files = list(REPO_ROOT.glob("*.md")) + list(REPO_ROOT.glob("docs/**/*.md"))
    
    for md_file in md_files:
        try:
            content = md_file.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
            
        match = FRONTMATTER_RE.match(content)
        if match:
            try:
                fm = yaml.safe_load(match.group(1)) or {}
                if "doc_id" in fm or "doc_class" in fm:
                    # Inject the relative path so the registry knows where it came from
                    fm["path"] = str(md_file.relative_to(REPO_ROOT))
                    entries.append(fm)
            except yaml.YAMLError:
                pass

    # Sort entries by doc_id to ensure determinism
    entries.sort(key=lambda x: str(x.get("doc_id", "")))
    return entries


def _md(value: Any) -> str:
    if value is None:
        return "—"
    text = str(value).replace("\n", " ").strip()
    if not text:
        return "—"
    return text.replace("|", "\\|")


def _compact(text: str | None) -> str:
    if not text:
        return "—"
    return " ".join(text.split())


def _render_registry_table(entries: list[dict[str, Any]]) -> str:
    lines = [
        "## Registry Table",
        "",
        "| doc_id | path | doc_class | authority_kind | title | primary_audience | status | notes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for entry in entries:
        lines.append(
            "| "
            + " | ".join(
                [
                    _md(entry.get("doc_id")),
                    _md(entry.get("path")),
                    _md(entry.get("doc_class")),
                    _md(entry.get("authority_kind")),
                    _md(entry.get("title")),
                    _md(entry.get("primary_audience")),
                    _md(entry.get("status")),
                    _md(_compact(entry.get("notes"))),
                ]
            )
            + " |"
        )
    return "\n".join(lines)


def _render_summary(entries: list[dict[str, Any]]) -> str:
    doc_class_counts = Counter(entry.get("doc_class") for entry in entries)
    authority_counts = Counter(
        entry.get("authority_kind")
        for entry in entries
        if entry.get("authority_kind") is not None
    )
    lines = [
        "## Coverage Summary",
        "",
        f"- **Total registered docs**: {len(entries)}",
        f"- **By `doc_class`**: "
        + ", ".join(f"`{key}`={doc_class_counts[key]}" for key in sorted(doc_class_counts)),
        f"- **By `authority_kind`**: "
        + ", ".join(f"`{key}`={authority_counts[key]}" for key in sorted(authority_counts)),
    ]
    return "\n".join(lines)


def _entry_docs_for_task(entries: list[dict[str, Any]]) -> dict[str, list[str]]:
    task_map: dict[str, list[str]] = defaultdict(list)
    for entry in entries:
        task_entry_for = entry.get("task_entry_for")
        if not isinstance(task_entry_for, list):
            continue
        for task_class in task_entry_for:
            task_map[str(task_class)].append(str(entry.get("doc_id")))
    return dict(sorted(task_map.items()))


def _render_task_routing(entries: list[dict[str, Any]]) -> str:
    task_map = _entry_docs_for_task(entries)
    lines = [
        "## Task Routing Quick Reference",
        "",
        "The registry assigns `task_entry_for` to help agents and humans find starting points.",
        "",
        "| Task Class | Declared Entry Doc(s) |",
        "|---|---|",
    ]
    for task_class, doc_ids in task_map.items():
        lines.append(
            f"| `{_md(task_class)}` | {', '.join(f'`{_md(doc_id)}`' for doc_id in doc_ids)} |"
        )
    return "\n".join(lines)


def render_registry_md(entries: list[dict[str, Any]]) -> str:
    parts = [
        "# Documentation Registry",
        "",
        "**Generated from:** Distributed Markdown Frontmatter",
        "**Generator:** `scripts/aggregate_registry.py`",
        "**Source of truth:** Markdown files themselves — do not edit this file directly.",
        "",
        "---",
        "",
        "## Governance Model Legend",
        "",
        "### doc_class",
        "",
        "| Value | Meaning |",
        "|---|---|",
        "| `entrypoint` | Navigation only — points to other docs, makes no factual claims |",
        "| `active` | Currently maintained documentation with named authority |",
        "| `generated` | Mechanically refreshed from source artifacts |",
        "| `historical` | Archived, superseded, or non-authoritative |",
        "",
        "### authority_kind (for active and generated docs)",
        "",
        "| Value | Meaning |",
        "|---|---|",
        "| `plan` | Goals, sequencing, decisions, prioritization |",
        "| `blueprint` | Intended design, expected implementation, interface contracts |",
        "| `guide` | Operational or development procedure |",
        "| `current_config` | What source artifacts currently define |",
        "| `runtime_evidence` | What has been verified in a running environment |",
        "| `null` | Not applicable (entrypoint or historical) |",
        "",
        "---",
        "",
        _render_summary(entries),
        "",
        "---",
        "",
        _render_registry_table(entries),
        "",
        "---",
        "",
        _render_task_routing(entries),
        "",
        "---",
        "",
        "## Regeneration",
        "",
        "Run `python scripts/aggregate_registry.py` after updating Markdown frontmatter.",
    ]
    return "\n".join(parts) + "\n"


def main() -> None:
    entries = extract_governed_entries()
    
    # Save cache for other scripts
    with REGISTRY_CACHE.open("w", encoding="utf-8") as f:
        json.dump({"entries": entries}, f, indent=2, default=str)
    
    # Generate human readable markdown
    output = render_registry_md(entries)
    REGISTRY_MD.parent.mkdir(parents=True, exist_ok=True)
    REGISTRY_MD.write_text(output, encoding="utf-8")
    
    print(f"Generated cache: {REGISTRY_CACHE.relative_to(REPO_ROOT)}")
    print(f"Generated markdown: {REGISTRY_MD.relative_to(REPO_ROOT)}")
    print(f"Entries aggregated: {len(entries)}")


if __name__ == "__main__":
    main()
