#!/usr/bin/env python3
"""Generate docs/reference/registry/DOC_REGISTRY.md from DOC_REGISTRY.yaml.

Run from repo root or any location:
    python scripts/build_doc_registry_md.py
"""

from __future__ import annotations

from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
from typing import Any

import yaml


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent  # scripts/ -> repo_root
REGISTRY_YAML = REPO_ROOT / "docs" / "reference" / "registry" / "DOC_REGISTRY.yaml"
REGISTRY_MD = REPO_ROOT / "docs" / "reference" / "registry" / "DOC_REGISTRY.md"


def load_registry_entries() -> list[dict[str, Any]]:
    try:
        with REGISTRY_YAML.open("r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
    except yaml.YAMLError:
        data = None

    if not isinstance(data, dict):
        raise ValueError(f"Root of {REGISTRY_YAML} must be a dictionary. Got malformed or empty file.")
        
    entries = data.get("entries")
    if not isinstance(entries, list):
        raise ValueError(f"'entries' missing or invalid in {REGISTRY_YAML}")
    return entries


def _md(value: Any) -> str:
    if value is None:
        return "—"
    text = str(value).replace("\n", " ").strip()
    if not text:
        return "—"
    return text.replace("|", "\\|")


def _compact(text: str | None) -> str:
    if not text:
        return "—"
    return " ".join(text.split())


def _render_registry_table(entries: list[dict[str, Any]]) -> str:
    lines = [
        "## Registry Table",
        "",
        "| doc_id | path | doc_class | authority_kind | title | primary_audience | status | notes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for entry in entries:
        lines.append(
            "| "
            + " | ".join(
                [
                    _md(entry.get("doc_id")),
                    _md(entry.get("path")),
                    _md(entry.get("doc_class")),
                    _md(entry.get("authority_kind")),
                    _md(entry.get("title")),
                    _md(entry.get("primary_audience")),
                    _md(entry.get("status")),
                    _md(_compact(entry.get("notes"))),
                ]
            )
            + " |"
        )
    return "\n".join(lines)


def _render_summary(entries: list[dict[str, Any]]) -> str:
    doc_class_counts = Counter(entry.get("doc_class") for entry in entries)
    authority_counts = Counter(
        entry.get("authority_kind")
        for entry in entries
        if entry.get("authority_kind") is not None
    )
    lines = [
        "## Coverage Summary",
        "",
        f"- **Total registered docs**: {len(entries)}",
        f"- **By `doc_class`**: "
        + ", ".join(f"`{key}`={doc_class_counts[key]}" for key in sorted(doc_class_counts)),
        f"- **By `authority_kind`**: "
        + ", ".join(f"`{key}`={authority_counts[key]}" for key in sorted(authority_counts)),
    ]
    return "\n".join(lines)


def _entry_docs_for_task(entries: list[dict[str, Any]]) -> dict[str, list[str]]:
    task_map: dict[str, list[str]] = defaultdict(list)
    for entry in entries:
        task_entry_for = entry.get("task_entry_for")
        if not isinstance(task_entry_for, list):
            continue
        for task_class in task_entry_for:
            task_map[str(task_class)].append(str(entry.get("doc_id")))
    return dict(sorted(task_map.items()))


def _render_task_routing(entries: list[dict[str, Any]]) -> str:
    task_map = _entry_docs_for_task(entries)
    lines = [
        "## Task Routing Quick Reference",
        "",
        "The registry assigns `task_entry_for` to help agents and humans find starting points.",
        "",
        "| Task Class | Declared Entry Doc(s) |",
        "|---|---|",
    ]
    for task_class, doc_ids in task_map.items():
        lines.append(
            f"| `{_md(task_class)}` | {', '.join(f'`{_md(doc_id)}`' for doc_id in doc_ids)} |"
        )
    return "\n".join(lines)


def render_registry_md(entries: list[dict[str, Any]]) -> str:
    today = date.today().isoformat()
    parts = [
        "# Documentation Registry",
        "",
        f"**Generated from:** `{REGISTRY_YAML.relative_to(REPO_ROOT)}`",
        f"**Generated:** {today}",
        "**Generator:** `scripts/build_doc_registry_md.py`",
        "**Source of truth:** DOC_REGISTRY.yaml — do not edit this file directly.",
        "",
        "---",
        "",
        "## Governance Model Legend",
        "",
        "### doc_class",
        "",
        "| Value | Meaning |",
        "|---|---|",
        "| `entrypoint` | Navigation only — points to other docs, makes no factual claims |",
        "| `active` | Currently maintained documentation with named authority |",
        "| `generated` | Mechanically refreshed from source artifacts |",
        "| `historical` | Archived, superseded, or non-authoritative |",
        "",
        "### authority_kind (for active and generated docs)",
        "",
        "| Value | Meaning |",
        "|---|---|",
        "| `plan` | Goals, sequencing, decisions, prioritization |",
        "| `blueprint` | Intended design, expected implementation, interface contracts |",
        "| `guide` | Operational or development procedure |",
        "| `current_config` | What source artifacts currently define |",
        "| `runtime_evidence` | What has been verified in a running environment |",
        "| `null` | Not applicable (entrypoint or historical) |",
        "",
        "---",
        "",
        _render_summary(entries),
        "",
        "---",
        "",
        _render_registry_table(entries),
        "",
        "---",
        "",
        _render_task_routing(entries),
        "",
        "---",
        "",
        "## Regeneration",
        "",
        "Run `python scripts/build_doc_registry_md.py` after updating `docs/reference/registry/DOC_REGISTRY.yaml`.",
    ]
    return "\n".join(parts) + "\n"


def main() -> None:
    entries = load_registry_entries()
    output = render_registry_md(entries)
    REGISTRY_MD.write_text(output, encoding="utf-8")
    print(f"Generated: {REGISTRY_MD.relative_to(REPO_ROOT)}")
    print(f"Entries rendered: {len(entries)}")


if __name__ == "__main__":
    main()
